completed scripts for project template

diff --git a/project-template/add-port-to-security-group b/project-template/add-port-to-security-group
--- a/project-template/add-port-to-security-group
+++ b/project-template/add-port-to-security-group
@@ -1,13 +1,38 @@
-# add-port-to-security-group
-# Get port number from command line and open it for incoming requests
-# in security group
-if [ -z $1 ]; then
-  echo "Usage: add-port-to-security-group <port number>"
-  exit 1
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# add-port-to-security-group - Get port number from command line and 
+#                              open it for incoming requests
+#
+# Usage: add-port-to-security-group [-h] -g sggroup-id -n port-number
+#
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+usage() { echo "Usage: add-port-to-security-group [-h] -g sggroup-id -n port-number";
+         echo "    sggroup-id is the ID of the security group";
+         echo "    port-number is the port to open for incoming traffic";
+         echo "    -h is the help option"; }
+GROUPID=""
+PORTNUM=""
+while getopts g:n:h opt; do
+    case $opt in
+        g) GROUPID=${OPTARG}
+        ;;
+        n) PORTNUM=${OPTARG}
+        ;;
+        h) usage; exit;
+        ;;
+    esac
+done
+if [ -z $GROUPID ]; then
+    echo "error: security group id is required. "
+    exit 1
+fi
+if [ -z $PORTNUM ]; then
+    echo "error: port number is required. "
+    exit 1
 fi
 aws ec2 authorize-security-group-ingress \
-    --group-id `cat ${AWS_CLI_WORK_DIR}/sggroup.txt` \
+    --group-id ${GROUPID} \
     --protocol tcp \
-    --port ${1} \
+    --port ${PORTNUM} \
     --cidr 0.0.0.0/0
+echo "Port ${PORTNUM} added to security group ID ${GROUPID}."
 
diff --git a/project-template/create-security-group b/project-template/create-security-group
--- a/project-template/create-security-group
+++ b/project-template/create-security-group
@@ -1,7 +1,40 @@
-aws ec2 create-security-group \
-    --group-name ${AWS_CLI_PROJECT_NAME}-sg \
-    --description "security group for ${AWS_CLI_PROJECT_NAME} project" \
-    --vpc-id `cat ${AWS_CLI_WORK_DIR}/vpcid.txt` \
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# create-security-group - create a security group
+#
+# Usage: create-security-group [-h] -v vpc-id [-p project-name]  
+#
+# Default: project-name = env variable AWS_CLI_PROJECT_NAME
+#
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+usage() { echo "Usage: create-security-group [-h] -v vpc-id [-p project-name]";
+         echo "    vpc-id is the VPC where the security group will belong"; 
+         echo "    project-name defaults to the env variable AWS_CLI_PROJECT_NAME"; 
+         echo "    -h is the help option"; }
+PROJECT=${AWS_CLI_PROJECT_NAME}
+VPCID=""
+while getopts v:p:h opt; do
+    case $opt in
+        v) VPCID=${OPTARG}
+        ;;
+        p) PROJECT=${OPTARG}
+        ;;
+        h) usage; exit;
+        ;;
+    esac
+done
+if [ -z $PROJECT ]; then
+    echo "error: project-name must be non-blank. "
+    exit 1
+fi
+if [ -z $VPCID ]; then
+    echo "error: vpc-id is required. "
+    exit 1
+fi
+GROUPID=`aws ec2 create-security-group \
+    --group-name ${PROJECT}-sg \
+    --description "security group for ${PROJECT} project" \
+    --vpc-id ${VPCID} \
     --query 'GroupId' \
-    --output text \
-    > ${AWS_CLI_WORK_DIR}/sggroup.txt
+    --output text`
+
+echo "Security group ${PROJECT}-sg created with ID ${GROUPID}" 
